### ISSUE TITLE
Wrong weekday!

### ISSUE THREAD

**Issue by mehranabi** [rghorbani/react-native-persian-calendar-picker#10]
Hello, Thanks for this good library,
Today is (سه‌شنبه 21 فروردین 1397) but library show today is (چهارشنبه 21 فروردین 1397) !
![screenshot_2018-04-10-19-07-25](https://user-images.githubusercontent.com/30838541/38563822-07bb550a-3cf3-11e8-95db-2bf4c68c3dae.png)

**Comment by MehranAbghari** [comment]
سلام، فکر کنم تمام تاریخ ها یک روز هفته جلو هستند، که با کد زیر قابل حل است:
(I think all days are one weekday ahead that can be fixed by this prop:)
`weekdays={['جمعه','شنبه','یک‌شنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنج‌شنبه']}`

**Comment by mehranabi** [comment]
This problem can be fixed by this prop:
`weekdays={['جمعه','شنبه','یک‌شنبه','دوشنبه','سه‌شنبه','چهارشنبه','پنج‌شنبه']}`

**Comment by rghorbani** [comment]
Fixed in 1.2.0
