### ISSUE TITLE
Throw error, when i used minDate and maxDate props.

### ISSUE THREAD

**Issue by mohammad-goldast** [rghorbani/react-native-persian-calendar-picker#11]
Hi everyone.
First of all, i must say Thank you Mr. @rghorbani for publish this valuable package.
As you know, when i wrote the below code, i received :
`Warning: Failed prop type: Invalid prop "minDate" of type "Date" supplied to "Days", expected instance of "jMoment".`

My code is here to checkout :

    class FreeTime extends Component { 
        constructor(props) {
            super(props);
            this.state = {
                date: new Date(),
                prevDay: (d => new Date(d.setDate(d.getDate() - 1)))(new Date()),
            };
            this.onDateChange = this.onDateChange.bind(this);
        }
    
        onDateChange(date) {
        this.setState({ date });
        }
        
        render() {
            const { date, prevDay} = this.state;
            return (
                <View style={styles.container}>
                    <NavBar
                        title={'انتخاب تاریخ'}
                        icon="ios-arrow-back-outline"
                        onPress={() => console.log('21')}
                    />
                    <PersianCalendarPicker
                        selectedDate={date}
                        onDateChange={this.onDateChange}
                        screenWidth={Dimensions.get('window').width}
                        minDate={prevDay}
                    />
            
            </View>
            );
        }
    }

My goal of using `minDate` is that the user will not be able to choose the days before the current date.
For this problem, what should i pass to `minDate`  props ?

Also when i want to limit user to choose only between next 7 days in `react-native-persian-calendar-picker`, what should i pass to `maxDate`  props ?

**Comment by rghorbani** [comment]
Hi,
There was a validation problem in one of the components. I have fixed it in 1.1.7
But I recommend using [react-native-general-calendars](https://github.com/rghorbani/react-native-general-calendars) since it has more features and it is more stable.
