### ISSUE TITLE
ایراد در تغییر ماه

### ISSUE THREAD

**Issue by ameer-taghavi** [rghorbani/react-native-persian-calendar-picker#13]
وقتی روز روی ۳۱ باشه و ماه بعد ۳۰ روز باشه، و روی ماه بعد تپ کنم، خطای تبدیل تاریخ  میده

**Comment by rghorbani** [comment]
@AmeerTgh Hi,
Please send me snippet of code to run and enviroment details (node and module versions).

**Comment by ameer-taghavi** [comment]
دقیقا بر اساس مثال شما پیش رفتم و هیچ کار خاصی نکردم. برای تست شما ۳۱ شهریور ر انتخاب کنید و به ماه بعد (مهر) برید. میبینید که خطای تبدیل تاریخ میده. در واقعه روی ۳۱ میمونه و ماه عوض میشه و چون ۳۱ مهر نداریم، خطا میده

با آخرین ورژن کامپوننت شما و ری‌اکت نیتیو تست کردم

**Comment by rghorbani** [comment]
@AmeerTgh Just released version [2.0.0](https://github.com/rghorbani/react-native-persian-calendar-picker/releases/tag/2.0.0).
* Added whole lot more capabilities.
* Fixed some bugs.

**Comment by ameer-taghavi** [comment]
👍🙏

**Comment by ameer-taghavi** [comment]
با تشکر
اگر برای مثال از شهریور به مهر بریم، ارتفاع تقویم کم و زیاد میشه. اگر ارتفاع ثابت باشه بهتره.
از height هم استفاده کردم ولی نشد

**Comment by rghorbani** [comment]
@AmeerTgh This is not an issue.
