### ISSUE TITLE
How to pic year?

### ISSUE THREAD

**Issue by reza7rm** [rghorbani/react-native-persian-calendar-picker#15]
Thank you very much for this great component, but is there any way of picking year?
for example to pick a date in 1365 what can I do?!

**Comment by rghorbani** [comment]
@reza7rm Thank you. It is possible by using `initialDate`.
`<PersianCalendarPicker initialDate="1992-01-01" isRTL />`.

**Comment by rghorbani** [comment]
@reza7rm Sorry year picking in not available but you are welcome to make a Pull Request.

**Comment by rghorbani** [comment]
If you just want year one the best ways would be using react native's `Picker`.
