### ISSUE TITLE
Some props not working

### ISSUE THREAD

**Issue by Kiarash-Z** [rghorbani/react-native-persian-calendar-picker#17]
HI thanks for the package. Some props like `selectedDayTextColor` or `selectedDayColor` aren't working at all...

React Native:  0.51.0
react: 16.0.0

**Comment by rghorbani** [comment]
Hi @Kiarash-Z 
Could you provide a snippet of the code?

**Comment by Kiarash-Z** [comment]
```
          <PersianCalendarPicker
              selectedDayTextColor ="#ffffff"
              onDateChange={date => {
              
              }}
              selectedDayStyle={{
                  backgroundColor: '#4E98DA'
              }}
          />
```

**Comment by rghorbani** [comment]
@Kiarash-Z Yep, found the problem, Willl be fixed soon.

**Comment by rghorbani** [comment]
I also refer you to new Styles section in readme
