### ISSUE TITLE
asyncstorage

### ISSUE THREAD

**Issue by bawhari** [rghorbani/react-native-persian-calendar-picker#19]
hi 
I'm in my project To take a picture https://reactnativecode.com/select-pick-image-capture-camera-gallery-react-native/ And the calendar of https://yarnpkg.com/en/package/react-native-persian-calendar-picker I use How can I save a picture with asyncstorage every day??? In fact, every day of the week the user chooses to take a specific photo or view

سلام من در پروژه ام 
برای گرفتن عکس 
https://reactnativecode.com/select-pick-image-capture-camera-gallery-react-native/
و تقویمم از
https://yarnpkg.com/en/package/react-native-persian-calendar-picker
استفاده می کنم
چطور می تونم با asyncstorage در هر روز مشخص یه عکس ذخیره کنم
در واقع هر روز هفته که کاربر انتخاب کرد یه عکس مشخص سیو کنه و یا ببینه
و مثلا اطلاعات روز 6مرداد با 5مرداد متفاوت باشه
ممون میشم اگه راهنماییم کنید

**Comment by rghorbani** [comment]
@bawhari This is not a place for such questions and I don't really understand your questions. If you are talking about taking screenshots, Have you considered running screenshot function when onDateChange is being called.
