### ISSUE TITLE
use datepicker as modal

### ISSUE THREAD

**Issue by m-jahanbakhsh** [rghorbani/react-native-persian-calendar-picker#20]
hello
how to use this calendar as modal?
if add isVisible that set true or false as props or other ways we can show/hide calendar ?

**Comment by alishonsafari** [comment]
> hello
> how to use this calendar as modal?
> if add isVisible that set true or false as props or other ways we can show/hide calendar ?


Hi
you can install modal or popup package and insert date picker into modal or popup,

suggest packages : 
[Modal](https://github.com/react-native-community/react-native-modal)
[Popup](https://www.npmjs.com/package/react-native-popup-dialog)

for example your code must be :
`
<Modal  isVisible={this.state.isModalVisible}>
`
`
   <PersianCalendarPicker />
`
`
</Modal>
`
