### ISSUE TITLE
Pervious dates

### ISSUE THREAD

**Issue by AmirTahani** [rghorbani/react-native-persian-calendar-picker#22]
How to select previous dates ? 
like 1297/2/13 ?

**Comment by rghorbani** [comment]
Hi @AmirTahani,
I don't get the problem exactly but I think your problem could be solved by setting the `initialDate` prop.

**Comment by hamidKhoshSafar** [comment]
` onDateChange(date) {`
  ` this.setState({ selectedStartDate: date.jYear() + "/" + (date.jMonth() + 1) + "/" + date.jDate() });` 
`}`

**Comment by rghorbani** [comment]
Hi, is the problem fixed?
