### ISSUE TITLE
selectedStartDate works strangely

### ISSUE THREAD

**Issue by HamedNN76** [rghorbani/react-native-persian-calendar-picker#24]
Hi Mr @rghorbani 
I am working on a project and I needed date picker so I used your package.
but in selectedStartDate prop I found a strange thing happening
The date picker convert the passed date to yesterday date for example if I pass "1350/6/18" to this props , the selected date in date picker would be "1350/6/17"
I checked my codes and there is no mutation or anything else
Please check this out.
This is badly stopping me.

**Comment by rghorbani** [comment]
Actually you should pass javascript's Date object like `new Date()`, not the jalaali date string.
