### ISSUE TITLE
disabledDates doesn't work !

### ISSUE THREAD

**Issue by vtorabian** [rghorbani/react-native-persian-calendar-picker#26]
i pass a date array to disabledDates but it doesn't work !

**Comment by rghorbani** [comment]
Hi @voogle, is the problem fixed?

**Comment by vtorabian** [comment]
> Hi @voogle, is the problem fixed?

hi , no it doesnt :(

**Comment by rghorbani** [comment]
@voogle What are you passing?
Accepted values are JS Date object or Gregorian date string e.g. "2017-04-25".

**Comment by hananf1994** [comment]
hi, how to change current date and selected day?
