### ISSUE TITLE
onSwipe in rtl need chagne direction

### ISSUE THREAD

**Issue by caspianprogrammer** [rghorbani/react-native-persian-calendar-picker#28]
```
 onSwipe(gestureName) {
    switch (gestureName) {
      case SWIPE_LEFT:
        this.handleOnPressNext();
        break;
      case SWIPE_RIGHT:
        this.handleOnPressPrevious();
        break;
    }
}

```
in line 191 in index need change when select rtl , I had to change the module manually

**Comment by javadi69** [comment]
Better to change like this:
<pre>
onSwipe(gestureName) {
    if (typeof this.props.onSwipe === 'function') {
      this.props.onSwipe(gestureName);
      return;
    }
    switch (gestureName) {
      case SWIPE_LEFT:
        if (this.props.isRTL) this.handleOnPressPrevious();
        else this.handleOnPressNext();
        break;
      case SWIPE_RIGHT:
        if (this.props.isRTL) this.handleOnPressNext();
        else this.handleOnPressPrevious();
        break;
    }
  }
</pre>

**Comment by rghorbani** [comment]
@javadi69 Could you create a PR?

**Comment by javadi69** [comment]
@rghorbani created. #33
