### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by seriiix** [rghorbani/react-native-persian-calendar-picker#30]
This package takes too much time to load and very slow to response especially on Android.

**Comment by rghorbani** [comment]
@seriiix Are you sure that this package is the cause of poor performance?

**Comment by seriiix** [comment]
Yeah. I'll provide an example with some gifs for comparison but basically, the delay on mid-range Android phones is not acceptable (the module takes ~2 seconds to load and ~0.5 seconds to response). However, it performs "fine" (still a little bit of delay) on high-end phones (tested on Galaxy S9, OnePlus 6T).
