### ISSUE TITLE
unexpected token

### ISSUE THREAD

**Issue by Schabaani** [rghorbani/react-native-persian-calendar-picker#7]
I got unexpected token in last version of react-native.
I copy/pasted all of your codes from here [npm](https://www.npmjs.com/package/react-native-persian-calendar-picker)

![screenshot_1517745990](https://user-images.githubusercontent.com/16123923/35777382-36489414-09c2-11e8-8a47-ec73015e1436.png)

**Comment by rghorbani** [comment]
Fixed in 1.1.1
